spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: baloo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update