spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: baloo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  secret: cThIIoDvwdueQB468K5xDc5633seEFoqwxjFsxSJyQQ
  expiration_time: 60000